version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./abstrackr:/app/abstrackr  # Mount the current directory to /app in the container
    environment:
      DB_HOST: <db_host>
      DB_PORT: <db_port>
      DB_USER: <db_user>
      DB_PASSWORD: <db_password>
      DB_NAME: <db_name>
      SMTP_HOST: <smtp_host>
      SMTP_PORT: <smtp_port>
      SMTP_USERNAME: <smtp_username>
      SMTP_PASSWORD: <smtp_password>
      SMTP_SENDER: <smtp_sender>
    command: ["paster", "serve", "--reload", "development.ini"]